---
- name: Playbook to demonstrate loops in Ansible
  hosts: devops
  become: yes
  tasks:

    - name: Install multiple packages
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - vim
        - wget

    - name: Create multiple users
      user:
        name: "{{ item }}"
        state: present
      loop:
        - Nikita
        - Mayur
        - Monali

    - name: Ensure directories exist
      file:
        path: "/tmp/{{ item }}"
        state: directory
      loop:
        - dir1
        - dir2
        - dir3
